project:
  type: website
  output-dir: docs
  
website:
  title: "Emily's Home Page"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/ejsimon0408/Website.git
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2025, Emily Simon"

format:
  html:
    theme: pulse
    toc: true

editor: source

